development:
  adapter: postgresql
  database: vinyl_dev
  pool: 5
  timeout: 5000
  username: my_user
  password: my_password
  host: localhost
  encoding: UTF8    
test:
  adapter: postgresql
  database: vinyl_test
  pool: 5
  timeout: 5000
  username: my_user
  password: my_password
  host: localhost
  encoding: UTF8    

production:
  adapter: postgresql
  database: vinyl
  pool: 5
  timeout: 5000
  username: my_user
  password: my_password
  host: localhost
  encoding: UTF8    

